[package]
name = "add_one"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
# 작업공간 내 크레이트들의 외부 의존성은 각각 지정해줘야 함
# 하나의 크레이트에서 지정했다고 다른 크레이트가 자동으로 쓸 수 있지 않음
# 하지만 작업공간의 Cargo.lock에서 같은 외부 의존성을 여러 크레이트에서 쓴다면 버전은 통일시킴
